### ISSUE TITLE
What is the procedure for keeping up to date?

### ISSUE THREAD

**Issue by dontlaugh** [christophgysin/aws-sdk-js-v3#1]
Thanks for taking a crack at this giant endeavour. I actually think the ops/infra/scripting use case is an area where Deno really shines.

1. How do you imagine we should keep this repo up to date? E.g. some practical steps for tracking upstream, rebasing, etc.
2. What difficulties have you encountered so far?
3. Have you considered alternative approaches to a fork of aws-sdk-js-v3? Specifically, a code generator that transforms an official sdk (maybe the Python or the Go sdk), into Javascript? The rusoto project does this for Rust.

Even if this remains experimental, it's still a valuable contribution to figuring out how to make an AWS sdk work. :+1:

**Comment by christophgysin** [comment]
Sorry for the late response, I somehow missed this.

I started working on this mosty to be able to use deno in AWS Lambda, instead of node.js. But I'm sure there will be many use cases that benefit from having access to the full AWS SDK.

1. So far, I have been manually pulling in new (gamma-) releases, merged them to my fork's master, run the copy-to-deno script, run some basic tests for clients I know worked before, and fixed any new issues. After that, I push a new tag (v0.0.x), which automatically creates a new release on deno.land.

2. If you look at copy-to-deno.js, you'll noticed that mostly relies on pattern-matching the existing code. If the upstream code changes, those patterns need to be updated. It's not difficult, but monkey work.

3. I'm not sure I follow. This is a fork of the official AWS Javascript SDK.

I'm happy to hear any suggestions on how we can improve AWS SDK support in deno, and hopefully even get it built in upstream at some point in the future.

**Comment by dontlaugh** [comment]
> Sorry for the late response, I somehow missed this.

No worries 😊. 

Regarding number 3, I was wondering if you had considered transpiling from Go or Python sdks. But if you're having success with porting JavaScript, that's great.

**Comment by christophgysin** [comment]
aws-sdk-js-v3 is written in typescript, which is also what Deno expects, so this seemed like the obvious choice.

Regarding keeping up to date: I will cleanup the existing commits, squash them, rebase on top of upstream's master and push them to a new branch `deno`. Currently there are a bunch of changes in the branch that cause merge conflicts, making it hard to keep in sync. Hopefully that will become easier afterwards.
